export const CARD_GET_ALL_REQUEST = "CARD_GET_ALL_REQUEST";
export const CARD_GET_ALL_SUCCESS = "CARD_GET_ALL_SUCCESS";
export const CHANGE_CARD = "CHANGE_CARD";
export const CARD_GET_ALL_FAIL = "CARD_GET_ALL_FAIL";
